export const metadata = {
  title: "Halaman Admin ETicket",
  description: "Generated by Next.js",
};

import AdminLayout from "./AdminLayout"; 

export default function Layout({ children }) {
  return <AdminLayout>{children}</AdminLayout>;
}
