export const metadata = {
  title: 'Profile Pengunjung',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    
      <main>{children}</main>
  )
}
